default_platform(:ios)

platform :ios do
  desc "Run tests"
  lane :test do
    run_tests(
      project: "COHRM.xcodeproj",
      scheme: "COHRM",
      device: "iPhone 15",
      code_coverage: true
    )
  end

  desc "Build for TestFlight"
  lane :beta do
    increment_build_number
    build_app(
      project: "COHRM.xcodeproj",
      scheme: "COHRM",
      export_method: "app-store"
    )
    upload_to_testflight(
      skip_waiting_for_build_processing: true
    )
  end

  desc "Deploy to App Store"
  lane :release do
    build_app(
      project: "COHRM.xcodeproj",
      scheme: "COHRM",
      export_method: "app-store"
    )
    upload_to_app_store(
      force: true,
      skip_screenshots: true,
      skip_metadata: false
    )
  end
end
